import { Inter } from 'next/font/google'; // npm -> comp -> static func
import '../../styles/globals.css';
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gradient-to-b from-blue-300 to-purple-400">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
